# Generated by Django 4.1.5 on 2023-01-31 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Author',
            new_name='Authors',
        ),
    ]
