# Generated by Django 4.1.5 on 2023-01-31 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_rename_authors_author'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
